# Generated by Django 4.0.3 on 2023-01-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_technician_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='technician',
            new_name='tech_name',
        ),
    ]
