# Generated by Django 4.0.3 on 2023-01-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_rename_vin_appointment_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
